// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR648zQpATGJFnA7N3nOYbywV8jrxLnFQ',
    appId: '1:617147240174:web:be7717aecd21a6e5a4adff',
    messagingSenderId: '617147240174',
    projectId: 'trivia-world-ea0ef',
    authDomain: 'trivia-world-ea0ef.firebaseapp.com',
    storageBucket: 'trivia-world-ea0ef.firebasestorage.app',
    measurementId: 'G-DVFY6T5TDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQWcgfEyMKncxJVc71sK1B7-YV2VSQhEA',
    appId: '1:617147240174:android:ceb6a547710be150a4adff',
    messagingSenderId: '617147240174',
    projectId: 'trivia-world-ea0ef',
    storageBucket: 'trivia-world-ea0ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2hVhbHyTWpMmFGilUGla-Ja_OBKQMIrI',
    appId: '1:617147240174:ios:ad38d7273e3083b1a4adff',
    messagingSenderId: '617147240174',
    projectId: 'trivia-world-ea0ef',
    storageBucket: 'trivia-world-ea0ef.firebasestorage.app',
    iosClientId: '617147240174-t6ieac3kt40p318bgvkk3k2f0enottvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.triviaWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2hVhbHyTWpMmFGilUGla-Ja_OBKQMIrI',
    appId: '1:617147240174:ios:ad38d7273e3083b1a4adff',
    messagingSenderId: '617147240174',
    projectId: 'trivia-world-ea0ef',
    storageBucket: 'trivia-world-ea0ef.firebasestorage.app',
    iosClientId: '617147240174-t6ieac3kt40p318bgvkk3k2f0enottvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.triviaWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR648zQpATGJFnA7N3nOYbywV8jrxLnFQ',
    appId: '1:617147240174:web:4d8899a85d1bf54da4adff',
    messagingSenderId: '617147240174',
    projectId: 'trivia-world-ea0ef',
    authDomain: 'trivia-world-ea0ef.firebaseapp.com',
    storageBucket: 'trivia-world-ea0ef.firebasestorage.app',
    measurementId: 'G-QWSC766YJ2',
  );
}
